export interface AppConfigConst {
  BACKEND_API_ROOT_URL:string;
  BACKEND_WEBPACK_URL:string;
  BACKEND_API:string;
  BACKEND_API_AUTHENTICATE_PATH:string;
  BACKEND_API_LOGOUT_PATH:string;
  CURRENT_USERNAME:string;
  CURRENT_AUTHORITIES:string[];
  IS_AUTHENTICATED:boolean;
  CURRENT_SECURITY_LOGIN:string;
  CURRENT_SECURITY_TOKEN:string;
  CURRENT_OPTIONS:any;
}
